In [1]:
import tqdm
import pandas as pd
import re
import numpy as np
import os
from collections import Counter
import pickle

## 통합 데이터 프레임

In [81]:
info = pd.read_csv('/content/drive/MyDrive/부산 공모전/데이터/자연관광 데이터/자연해양관광.csv')

In [82]:
info.head(2)

순위     관광지명  광역시/도 시/군/구                 도로명주소 중분류 카테고리     소분류 카테고리  \
0   1  광안리해수욕장  부산광역시   수영구    부산 수영구 광안해변로 219-0     자연관광  자연경관(하천/해양)   
1   2  해운대해수욕장  부산광역시  해운대구  부산 해운대구 해운대해변로 264-0     자연관광  자연경관(하천/해양)   

     검색건수  
0  261818  
1  261722

In [83]:
info.shape

(109, 8)

In [84]:
names = list(info['관광지명'].values)
names[:5]

['광안리해수욕장', '해운대해수욕장', '송정해수욕장', '다대포해수욕장', '송도해수욕장']

In [85]:
text = []
for file in names:
  with open(f'/content/drive/MyDrive/부산 공모전/데이터/자연관광 데이터/realpickles/{file}_words.pkl','rb') as f:
    place = pickle.load(f)
    place = ' '.join(place)
    text.append(place)

In [21]:
text[1]

'대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울 예전 동해 요번 서해 남해 동해 남쪽 상대 날씨 매력 요소 고층 대형 생각 서해 동해 도심 부분 이색 매력 겨울 생각 대신 여름 느낌 날씨 대부분 갈매기 무리 부분 장악 동해 서해 갈매기 해변가 마을 수준 정착 수욕 느낌 겨울 갈매기 단체 편안 오후 갈매기 모이 먹이 야생 배설물 유의 서해 남해 매력 해수욕 시즌 파도 모래사장 겨울 남쪽 추위 구조물 배 등대 고정 노을 겨울 일부 일몰 겨울 오후 시점 하늘 노을 시점 장소 사진 고층 겨울 매력 일몰 생각 겨울 사진 빛 축제 부분 소개 빛 축제 진행 사실 생각 범위 설치 부분 소개 노을 밤 이유 빛 축제 구조물 미디어 활용 불빛 밤 사진 인파 대비 수용 인원 이내 수준 통제 일몰 오후 밤 여유 부족 삼각대 피곤 야경 다양 담지 삼각대 영상 영상 재생 물고기 영상 인상 광화문 토끼 복주머니 계묘 행복 기원 토끼 빛 축제 하루 겨울 일몰 밤 빛 축제 우동 바닷가 연예인 조세호 조개 구이 맛집 새호 지난번 새호 퀴즈 조세호 해운 대점 소식 폭발 가맹점 지점 유행 방증 맛집 새호 엘시티 레드 시즈 바닷가 모래사장 조개 구이 새호 직영 외관 출입구 천막 조개 구이 사진 첨부 조개 구이 맛집 새호 각종 성호 라인 지하 지원 나이스 매장 내부 층고 조개 구이 느낌 맛집 새호 직영 매장 오픈 동시 오픈 매장 계속 손님 가족 단위 데이트 커플 친구 다양 계층 평일 만석 웨이팅 인기 한몫 새호 직영 메뉴판 상호 조개 새우 메인 조개 구이 주문 해물 주문 완료 주문 기본 고기 애기 식판 당근 배추 후르츠 칵테일 옥수수 옥수수 저건 조개 구이 생각 반찬 미역국 스파게티 미역국 특이 북어 소고기 생선 조개 미역국 북어 순간 시원 밤 조개 구이 미역국 스파게티 본격 푸파 예열 해물 해물 판매 조개 구이 쥬얼 전복 새우 가리비 홍합 구성 성비 냄새 해산물 접시 금색 도시락 뚜껑 손잡이 아이템 가리비 전복 사진 박제 환장 나인데 조개 해산물 국물 천국 천국

In [86]:
print(len(text))
print(len(names))

109
109


In [87]:
text_df = pd.DataFrame({'관광지명':names,'text':text})
text_df.head(2)

관광지명                                               text
0  광안리해수욕장  여울 문화 마을 주소 영선동 여러분 명소 추억 여울 문화 마을 장소 여울 문화 마을...
1  해운대해수욕장  대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울...

In [88]:
df = pd.merge(info, text_df, on = '관광지명', how = 'inner')
df.head(2)

순위     관광지명  광역시/도 시/군/구                 도로명주소 중분류 카테고리     소분류 카테고리  \
0   1  광안리해수욕장  부산광역시   수영구    부산 수영구 광안해변로 219-0     자연관광  자연경관(하천/해양)   
1   2  해운대해수욕장  부산광역시  해운대구  부산 해운대구 해운대해변로 264-0     자연관광  자연경관(하천/해양)   

     검색건수                                               text  
0  261818  여울 문화 마을 주소 영선동 여러분 명소 추억 여울 문화 마을 장소 여울 문화 마을...  
1  261722  대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울...

In [89]:
df.shape

(109, 9)

In [90]:
df.isna().sum().sum()

0

In [27]:
df.to_csv('/content/drive/MyDrive/부산 공모전/데이터/자연관광 데이터/통합df.csv', index = False)

## 텍스트 군집화
https://romg2.github.io/mlguide/03_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C-08.-%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%B6%84%EC%84%9D-%EB%AC%B8%EC%84%9C-%EA%B5%B0%EC%A7%91%ED%99%94/#511-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0

In [28]:
df = pd.read_csv('/content/drive/MyDrive/부산 공모전/데이터/자연관광 데이터/통합df.csv')

In [34]:
df.loc[df['text'].isna()]

순위    관광지명  광역시/도 시/군/구  도로명주소 중분류 카테고리     소분류 카테고리  검색건수 text
38  46  감천동편부두  부산광역시    서구  부산 서구     자연관광  자연경관(하천/해양)  3735  NaN

In [38]:
df.dropna(axis = 0, inplace = True)
df.reset_index(drop = True, inplace = True)

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer
# 피처 벡터화 
tfidf = TfidfVectorizer(min_df=0.1)
feature_vect= tfidf.fit_transform(df['text'])
print(feature_vect.shape)

(109, 8308)


In [92]:
from sklearn.cluster import KMeans

# KMeans: 10
km_cluster = KMeans(n_clusters=10, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)

# cluster 및 중심 좌표 정보
cluster_label = km_cluster.labels_
cluster_centers = km_cluster.cluster_centers_

# cluster 라벨 추가
df['cluster_label'] = cluster_label
df.head()

순위     관광지명  광역시/도 시/군/구                 도로명주소 중분류 카테고리     소분류 카테고리  \
0   1  광안리해수욕장  부산광역시   수영구    부산 수영구 광안해변로 219-0     자연관광  자연경관(하천/해양)   
1   2  해운대해수욕장  부산광역시  해운대구  부산 해운대구 해운대해변로 264-0     자연관광  자연경관(하천/해양)   
2   3   송정해수욕장  부산광역시  해운대구    부산 해운대구 송정해변로 62-0     자연관광  자연경관(하천/해양)   
3   4  다대포해수욕장  부산광역시   사하구     부산 사하구 몰운대1길 14-0     자연관광  자연경관(하천/해양)   
4   5   송도해수욕장  부산광역시    서구                 부산 서구     자연관광  자연경관(하천/해양)   

     검색건수                                               text  cluster_label  
0  261818  여울 문화 마을 주소 영선동 여러분 명소 추억 여울 문화 마을 장소 여울 문화 마을...              9  
1  261722  대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울...              9  
2  244851  기록 숙소 근처 이마트 샌드위치 삼각김밥 서핑 지하철 배차 간격 체크 여유 어제 이...              2  
3  144834  오랜만 대구 남쪽 마음 동생 비교 메인 소개 일몰 명소 일대 소개 공원 규모 군데 ...              9  
4  119540  오션 뷰 숙소 호텔 내산 후기 장단점 가격 숙소 업그레이드 조식 예약 안녕 최근 이...              8

In [93]:
cluster_centers = km_cluster.cluster_centers_

print('cluster_centers shape :', cluster_centers.shape)
print(cluster_centers)

cluster_centers shape : (10, 8308)
[[0.         0.03491491 0.00352683 ... 0.00214104 0.00619972 0.00843143]
 [0.00065362 0.0294425  0.00270695 ... 0.00214    0.0007336  0.01923037]
 [0.         0.03589874 0.00369281 ... 0.00590353 0.         0.02297515]
 ...
 [0.00048625 0.01383722 0.00321551 ... 0.00444838 0.00251919 0.01753564]
 [0.         0.02284684 0.         ... 0.         0.         0.0087028 ]
 [0.00046201 0.03206925 0.00263696 ... 0.00063606 0.00156097 0.01975574]]


In [94]:
def get_cluster_details(cluster_model, cluster_data, cluster_nums, 
                        feature_names, top_n_features=10):
    
    # 핵심 단어 등 정보를 담을 사전 생성
    cluster_details = {}
    
    # word 피처 중심과의 거리 내림차순 정렬시 값들의 index 반환
    center_info = cluster_model.cluster_centers_        # 군집 중심 정보
    center_descend_ind = center_info.argsort()[:, ::-1] # 행별(군집별)로 역순 정렬
    
    # 군집별 정보 담기
    for i in range(cluster_nums):
        # 군집별 정보를 담을 데이터 초기화
        cluster_details[i] = {} # 사전 안에 사전
        
        # 각 군집에 속하는 파일명
        filenames = cluster_data[cluster_data["cluster_label"] == i]["관광지명"]
        filenames = filenames.values.tolist()
        
        # 군집별 중심 정보
        top_feature_values = center_info[i, :top_n_features].tolist()

        # 군집별 핵심 단어 피처명
        top_feature_indexes = center_descend_ind[i, :top_n_features]
        top_features = [feature_names[ind] for ind in top_feature_indexes]
        
        # 각 군집별 정보 사전에 담기
        cluster_details[i]["cluster"] = i                              # i번째 군집
        cluster_details[i]["top_features"] = top_features              # 군집별 핵심 단어
        cluster_details[i]["top_feature_values"] = top_feature_values  # 군집별 중심 정보
        cluster_details[i]["관광지명"] = filenames                    # 군집 속 파일명
        
    return cluster_details

In [95]:
# TF-IDF 객체의 전체 word 명칭
feature_names = tfidf.get_feature_names()

# 함수 적용
cluster_details = get_cluster_details(cluster_model=km_cluster, cluster_data=df, cluster_nums=10,
                                  feature_names=feature_names, top_n_features=10 )

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [96]:
cluster_details.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
cluster_details[0]

{'cluster': 0,
 'top_features': ['낚시', '카페', '사진', '생각', '공원', '대교', '촬영', '동진', '미끼', '시장'],
 'top_feature_values': [0.0,
  0.034914911168068455,
  0.0035268299905851785,
  0.002778101684046898,
  0.0,
  0.0005861930791782169,
  0.0,
  0.0,
  0.0007239667558103288,
  0.0],
 '관광지명': ['우동항', '일자방파제', '북빈물량장대체부두']}

In [99]:
for cluster_num, cluster_detail in cluster_details.items():
        print(f"####### Cluster {cluster_num}")
        print(f"Top features: {cluster_detail['top_features']}")
        print(f"Reviews 관광지명: {cluster_detail['관광지명'][:3]}")
        print("-"*120)

####### Cluster 0
Top features: ['낚시', '카페', '사진', '생각', '공원', '대교', '촬영', '동진', '미끼', '시장']
Reviews 관광지명: ['우동항', '일자방파제', '북빈물량장대체부두']
------------------------------------------------------------------------------------------------------------------------
####### Cluster 1
Top features: ['카페', '멸치', '마을', '맛집', '공원', '사진', '등대', '시장', '커피', '생각']
Reviews 관광지명: ['대변항', '회동저수지', '대변방파제']
------------------------------------------------------------------------------------------------------------------------
####### Cluster 2
Top features: ['열차', '캡슐', '다릿돌', '라인파크', '사진', '스카이', '정거장', '블루', '전망대', '카페']
Reviews 관광지명: ['송정해수욕장', '청사포방파제', '미포항']
------------------------------------------------------------------------------------------------------------------------
####### Cluster 3
Top features: ['대교', '사진', '공원', '야경', '항만', '마을', '버스', '등대', '터미널', '시장']
Reviews 관광지명: ['신선대부두', '감만부두', '부산항제7부두']
-----------------------------------------------------------------------------------------

In [112]:
df

순위       관광지명  광역시/도 시/군/구                 도로명주소 중분류 카테고리     소분류 카테고리  \
0      1    광안리해수욕장  부산광역시   수영구    부산 수영구 광안해변로 219-0     자연관광  자연경관(하천/해양)   
1      2    해운대해수욕장  부산광역시  해운대구  부산 해운대구 해운대해변로 264-0     자연관광  자연경관(하천/해양)   
2      3     송정해수욕장  부산광역시  해운대구    부산 해운대구 송정해변로 62-0     자연관광  자연경관(하천/해양)   
3      4    다대포해수욕장  부산광역시   사하구     부산 사하구 몰운대1길 14-0     자연관광  자연경관(하천/해양)   
4      5     송도해수욕장  부산광역시    서구                 부산 서구     자연관광  자연경관(하천/해양)   
..   ...        ...    ...   ...                   ...      ...          ...   
104  136  북빈물량장대체부두  부산광역시   영도구                부산 영도구     자연관광  자연경관(하천/해양)   
105  137     다대포방파제  부산광역시   사하구                부산 사하구     자연관광  자연경관(하천/해양)   
106  139        신암항  부산광역시   기장군     부산 기장군 연화1길 184-0     자연관광  자연경관(하천/해양)   
107  141    북항대교방파제  부산광역시   영도구    부산 영도구 해양로15번길 0-0     자연관광  자연경관(하천/해양)   
108  143       구덕포항  부산광역시  해운대구               부산 해운대구     자연관광  자연경관(하천/해양)   

       검색건수                                               text  cluster_label  \
0    261818  여울 문화 마을 주소 영선동 여러분 명소 추억 여울 문화 마을 장소 여울 문화 마을...              9   
1    261722  대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울...              9   
2    244851  기록 숙소 근처 이마트 샌드위치 삼각김밥 서핑 지하철 배차 간격 체크 여유 어제 이...              2   
3    144834  오랜만 대구 남쪽 마음 동생 비교 메인 소개 일몰 명소 일대 소개 공원 규모 군데 ...              9   
4    119540  오션 뷰 숙소 호텔 내산 후기 장단점 가격 숙소 업그레이드 조식 예약 안녕 최근 이...              8   
..      ...                                                ...            ...   
104      46  안녕 하루 무더위 개월 개월 낚시 구름 낚시 아내 아점 봉지 낚시 낚시 생활 낚시 ...              0   
105      43  여름 여름 휴가철 도심 도로 북새통 올해 상황 사회 두기 단계 적용 긴장감 사회 두...              9   
106      38  이모 동생 여자 해물 아침 조식 숙소 근처 바닷가 바닷가 정박 배 풍경 구름 다리 ...              1   
107      33  셋째 산책로 공원 호텔 토스트 시리얼 아침 식사 산책로 보건 고등학교 보건 담벼락 ...              4   
108      30  근처 파도 여름 밤 바람 노을 행복 카페 이야기 하루 바닷길 기차 구경 카페 음식점...              2   

     cluster  
0          5  
1          5  
2          3  
3          5  
4          3  
..       ...  
104        1  
105        5  
106        2  
107        4  
108        3  

[109 rows x 11 columns]

군집화 데이터프레임

In [111]:
df.loc[(df['cluster_label'] == 0) | (df['cluster_label'] == 7), 'cluster'] = 1
df.loc[(df['cluster_label'] == 1) | (df['cluster_label'] == 6), 'cluster'] = 2
df.loc[(df['cluster_label'] == 2) | (df['cluster_label'] == 8), 'cluster'] = 3
df.loc[(df['cluster_label'] == 3) | (df['cluster_label'] == 4), 'cluster'] = 4
df.loc[(df['cluster_label'] == 9), 'cluster'] = 5
df.loc[(df['cluster_label'] == 5), 'cluster'] = 6

## 위경도 추가

In [113]:
po = pd.read_csv('/content/drive/MyDrive/부산 공모전/데이터/위경도 데이터.csv')

In [115]:
po = po[['관광지명', '위도', '경도']]

In [116]:
po.head(2)

관광지명         위도          경도
0  광안리해수욕장  35.154255  129.119177
1  해운대해수욕장  35.159314  129.159885

In [118]:
df = pd.merge(df, po, on = '관광지명', how = 'inner')
df.head(2)

순위     관광지명  광역시/도 시/군/구                 도로명주소 중분류 카테고리     소분류 카테고리  \
0   1  광안리해수욕장  부산광역시   수영구    부산 수영구 광안해변로 219-0     자연관광  자연경관(하천/해양)   
1   2  해운대해수욕장  부산광역시  해운대구  부산 해운대구 해운대해변로 264-0     자연관광  자연경관(하천/해양)   

     검색건수                                               text  cluster_label  \
0  261818  여울 문화 마을 주소 영선동 여러분 명소 추억 여울 문화 마을 장소 여울 문화 마을...              9   
1  261722  대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울...              9   

   cluster         위도          경도  
0        5  35.154255  129.119177  
1        5  35.159314  129.159885

## 키워드 5개 추가

In [ ]:
key = []
for file in names:
  with open(f'/content/drive/MyDrive/부산 공모전/데이터/자연관광 데이터/nounsdict/{file}.pkl','rb') as f:
    place = pickle.load(f)
    word = []
    for i in range(min(len(place),5)):
      word.append(place[i][0])

    word = ' '.join(word)
    key.append(word)
key

['대교 사진 야경 숙소 공원',
 '축제 모래 사진 호텔 빛',
 '열차 서핑 토스트 사진 카페',
 '사진 일몰 공원 분수 생각',
 '케이블카 사진 구름다리 공원 산책로',
 '카페 사진 맛집 뷰 생각',
 '멸치 사진 맛집 등대 횟집',
 '공원 대교 야경 사진 버스',
 '마을 공원 전망대 문화 대교',
 '태종대 영화 성당 공원 시장',
 '카페 사진 아이 생각 뷰',
 '전망대 열차 사진 다릿돌 스카이',
 '사진 산책 마루 하우스 호텔',
 '공원 마을 대교 섬 사진',
 '대교 공원 버스 야경 사진',
 '낚시 공원 마을 캠핑 사진',
 '마을 카페 동굴 사진 역사',
 '사진 야경 대교 마을 배',
 '스카이 워크 공원 섬 사진',
 '장어 해산물 맛집 뷰 카페',
 '공원 마을 문화 시장 사진',
 '사진 전망대 마을 카페 어묵',
 '카페 마을 산책 사진 맛집',
 '등대 카페 칠암 야구 맛집',
 '마을 공원 동굴 사진 전망대',
 '공원 낚시 산책로 섬 전망대',
 '사진 마을 말 카페 생각',
 '마을 문화 공원 사진 전망대',
 '공원 낙동강 생태 철새 사진',
 '공원 대교 야경 사진 버스',
 '불꽃 축제 공원 시장 영화',
 '멸치 등대 마을 맛집 공원',
 '공원 산 아이 등산 산행',
 '사진 카페 스카이 숙소 뷰',
 '사진 마을 유엔 풍경 언덕',
 '공원 마을 산책로 전망대 풍경',
 '마을 펜션 낚시 공원 등대',
 '멸치 카페 맛집 축제 등대',
 '',
 '등대 야구 카페 사진 붕장어',
 '성당 사진 드라마 카페 촬영',
 '캠핑 사진 낚시 맛집 공원',
 '서핑 등대 마을 펜션 사진',
 '작품 전시 비엔날레 마을 공원',
 '마을 카페 생각 맛집 버스',
 '카페 식당 맛집 사진 뷰',
 '마을 봉래산 대교 캠핑 카페',
 '시장 공원 아파트 버스 교육',
 '사진 시장 카페 맛집 마을',
 '공원 터미널 항만 승선 등대',
 '섬 마을 공원 버스 조선',
 '공원 마을 박물관 명소 숲',
 '장어 시장 대

In [ ]:
len(key)

109

In [ ]:
key_df = pd.DataFrame({'관광지명':names,'키워드':key})
key_df.head(2)

관광지명             키워드
0  광안리해수욕장  대교 사진 야경 숙소 공원
1  해운대해수욕장   축제 모래 사진 호텔 빛

In [ ]:
final_df = pd.merge(df, key_df, on = '관광지명', how = 'inner')
final_df.head(2)

순위     관광지명  광역시/도 시/군/구                 도로명주소 중분류 카테고리     소분류 카테고리  \
0   1  광안리해수욕장  부산광역시   수영구    부산 수영구 광안해변로 219-0     자연관광  자연경관(하천/해양)   
1   2  해운대해수욕장  부산광역시  해운대구  부산 해운대구 해운대해변로 264-0     자연관광  자연경관(하천/해양)   

     검색건수                                               text  cluster_label  \
0  261818  여울 문화 마을 주소 영선동 여러분 명소 추억 여울 문화 마을 장소 여울 문화 마을...              9   
1  261722  대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울...              9   

   cluster         위도          경도             키워드  
0        5  35.154255  129.119177  대교 사진 야경 숙소 공원  
1        5  35.159314  129.159885   축제 모래 사진 호텔 빛

In [142]:
final_df.isna().sum().sum()

0

In [143]:
final_df

순위       관광지명  광역시/도 시/군/구                 도로명주소 중분류 카테고리     소분류 카테고리  \
0      1    광안리해수욕장  부산광역시   수영구    부산 수영구 광안해변로 219-0     자연관광  자연경관(하천/해양)   
1      2    해운대해수욕장  부산광역시  해운대구  부산 해운대구 해운대해변로 264-0     자연관광  자연경관(하천/해양)   
2      3     송정해수욕장  부산광역시  해운대구    부산 해운대구 송정해변로 62-0     자연관광  자연경관(하천/해양)   
3      4    다대포해수욕장  부산광역시   사하구     부산 사하구 몰운대1길 14-0     자연관광  자연경관(하천/해양)   
4      5     송도해수욕장  부산광역시    서구                 부산 서구     자연관광  자연경관(하천/해양)   
..   ...        ...    ...   ...                   ...      ...          ...   
104  136  북빈물량장대체부두  부산광역시   영도구                부산 영도구     자연관광  자연경관(하천/해양)   
105  137     다대포방파제  부산광역시   사하구                부산 사하구     자연관광  자연경관(하천/해양)   
106  139        신암항  부산광역시   기장군     부산 기장군 연화1길 184-0     자연관광  자연경관(하천/해양)   
107  141    북항대교방파제  부산광역시   영도구    부산 영도구 해양로15번길 0-0     자연관광  자연경관(하천/해양)   
108  143       구덕포항  부산광역시  해운대구               부산 해운대구     자연관광  자연경관(하천/해양)   

       검색건수                                               text  cluster_label  \
0    261818  여울 문화 마을 주소 영선동 여러분 명소 추억 여울 문화 마을 장소 여울 문화 마을...              9   
1    261722  대표 명소 여름 각종 축제 진행 겨울 일몰 빛 축제 진행 주소 우동 기간 요즘 겨울...              9   
2    244851  기록 숙소 근처 이마트 샌드위치 삼각김밥 서핑 지하철 배차 간격 체크 여유 어제 이...              2   
3    144834  오랜만 대구 남쪽 마음 동생 비교 메인 소개 일몰 명소 일대 소개 공원 규모 군데 ...              9   
4    119540  오션 뷰 숙소 호텔 내산 후기 장단점 가격 숙소 업그레이드 조식 예약 안녕 최근 이...              8   
..      ...                                                ...            ...   
104      46  안녕 하루 무더위 개월 개월 낚시 구름 낚시 아내 아점 봉지 낚시 낚시 생활 낚시 ...              0   
105      43  여름 여름 휴가철 도심 도로 북새통 올해 상황 사회 두기 단계 적용 긴장감 사회 두...              9   
106      38  이모 동생 여자 해물 아침 조식 숙소 근처 바닷가 바닷가 정박 배 풍경 구름 다리 ...              1   
107      33  셋째 산책로 공원 호텔 토스트 시리얼 아침 식사 산책로 보건 고등학교 보건 담벼락 ...              4   
108      30  근처 파도 여름 밤 바람 노을 행복 카페 이야기 하루 바닷길 기차 구경 카페 음식점...              2   

     cluster         위도          경도                  키워드  
0          5  35.154255  129.119177       대교 사진 야경 숙소 공원  
1          5  35.159314  129.159885        축제 모래 사진 호텔 빛  
2          3  35.177123  129.200198      열차 서핑 토스트 사진 카페  
3          5  35.047043  128.962353       사진 일몰 공원 분수 생각  
4          3  35.075490  129.016738  케이블카 사진 구름다리 공원 산책로  
..       ...        ...         ...                  ...  
104        1  35.087033  129.075704       낚시 카페 촬영 사진 커피  
105        5  35.052341  128.974835       사진 공원 마을 생각 문화  
106        2  35.347075  129.324871     등대 마을 해녀 해산물 전복죽  
107        4  35.103881  129.062717      공원 대교 문화 마을 전망대  
108        3  35.169428  129.196068      카페 전망대 열차 커피 사진  

[109 rows x 14 columns]

In [145]:
final_df.to_csv('/content/drive/MyDrive/부산 공모전/데이터/final_df.csv', index = False)

## 확인

In [ ]:
with open('/content/drive/MyDrive/부산 공모전/데이터/자연관광 데이터/realpickles/다대포해수욕장_words.pkl','rb') as f:
        place = pickle.load(f)
place[:5]

['오랜만', '대구', '남쪽', '마음', '동생']

In [137]:
with open('/content/drive/MyDrive/부산 공모전/데이터/자연관광 데이터/nounsdict/광안리해수욕장.pkl','rb') as f:
        place = pickle.load(f)
place[:5]

[('대교', 229), ('사진', 225), ('야경', 138), ('숙소', 132), ('공원', 104)]